version: '3.3'
services:

  postgresql-db-mangorhodes:
    image: 'bitnami/postgresql:12.4.0'
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: './postgresql_master_data'
        target: '/opt/bitnami/postgresql/data'
    environment:
      - POSTGRESQL_DATABASE=mangorhodes_primary
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=root
    restart: on-failure

  mangorhodes-main:
    image: stahlferro/mangorhodes-docker
    depends_on:
      - postgresql-db-mangorhodes
    hostname: mangorhodes-host
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql-db-mangorhodes:5432/mangorhodes_primary
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - JWT_SECRET=mangorhodes
    restart: on-failure
