alter table department add column creation_timestamp datetime(6);
alter table department add column modification_time_stamp datetime(6);
alter table keycard add column creation_timestamp datetime(6);
alter table keycard add column modification_time_stamp datetime(6);
alter table keycard_category add column creation_timestamp datetime(6);
alter table keycard_category add column modification_time_stamp datetime(6);
alter table operator add column creation_timestamp datetime(6);
alter table room add column creation_timestamp datetime(6);
alter table room add column modification_time_stamp datetime(6);
